### ISSUE TITLE
Was not able to complete a transfer until I added https://*.globusonline.org to the referenced line.

### ISSUE THREAD

**Issue by kodiakseraphim** [globus/static-search-portal#257]
https://github.com/globus/static-search-portal/blob/050824658eff686d44e02632268436e169e433a5/src/pages/_document.tsx#L13

**Comment by jbottigliero** [comment]
Thanks @kodiakseraphim – I've updated the default CSP to include this host in #258. It'll be tagged in v1.3.1.

**Comment by kodiakseraphim** [comment]
You're welcome! God bless you, and have a good weekend.
